### ISSUE TITLE
ALPHA - Error while handling the exception

### ISSUE THREAD

**Issue by Bloodrayne1995** [stargate-rewritten/Stargate-Bukkit#145] opened 2022-04-23 17:10 UTC
Hi,

as mentioned in Discord ([Link](https://discord.com/channels/853659042799026177/853662140619948053/967468254014607400)), we tested the Alpha-Build of Stargate. Everything works fine, but we get random these exception:

`[18:43:15 WARN]: [Stargate] Plugin Stargate v1.0.0.4-ALPHA generated an exception whilst handling plugin message
java.lang.NullPointerException: Cannot invoke "net.TheDgtl.Stargate.property.PluginChannel.ordinal()" because the return value of "net.TheDgtl.Stargate.property.PluginChannel.parse(String)" is null
        at net.TheDgtl.Stargate.listeners.StargateBungeePluginMessageListener.onPluginMessageReceived(StargateBungeePluginMessageListener.java:92) ~[Stargate-1.0.0.4-ALPHA.jar:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomPayload(ServerGamePacketListenerImpl.java:3217) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-301]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-301]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-301]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-301]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-301]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-301]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-301]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-301]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

Looks like a bungee related problem to us. 

**Our plugin list (everything got yesterday updated):**

- AreaShop, 
- AsyncWorldEdit, 
- AutomaticSchematicInserter, 
- BungeeTabListPlus, 
- ChestShop, 
- Citizens, 
- CMILib, 
- CommandAPI, 
- CraftBook, 
- dynmap, 
- EditableSign, 
- EoJumper, 
- EonaWarp, 
- Essentials, 
- EssentialsChat,
- EssentialsGeoIP, 
- EssentialsProtect, 
- EssentialsSpawn, 
- HeadDatabase, 
- HolographicDisplays, 
- HolographicExtension, 
- Jobs, 
- LuckPerms, 
- LWC, 
- Multiverse-Core, 
- Multiverse-NetherPortals, 
- PlaceholderAPI, 
- ProtocolLib, 
- ServerSigns, 
- Stargate, 
- Vault, 
- WorldBorder, 
- WorldEdit, 
- WorldGuard

**ServerVersion (/version output):** 
This server is running Paper version git-Paper-301 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: c449f6a)

**Waterfall (Bungee) Version:**
waterfall-1.18-483

-------------------- 

Except this message everything works fine. Great work

Greetings
Bloodrayne1995

**Comment by EpicKnarvik97** [comment] 2022-04-23 17:47
This seems to have been caused by a mistaken assumption when checking which sub-channel a BungeeCord message is received on. This hasn't appeared in testing as Stargate is usually the only BungeeCord plugin used. I've added a commit to the dev branch to ensure that BungeeCord messages on random sub-channels will be silently ignored.

**Comment by EpicKnarvik97** [comment] 2022-05-22 21:31
As @Thorinwasher confirmed the commit fixed the problem, I'm closing this issue.

**Closed as completed by EpicKnarvik97** 2022-05-22 21:31 UTC
Labels: issue, TMS
